'use strict';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>`<svg class="icon" aria-hidden="true"><use href="#i-${n}"/></svg>`;
const S={stations:[],cases:[],regions:[],city:'강릉',query:'',limit:6,page:'home',station:null,map:null,session:null,strategy:null,filter:'전체',feedback:new Set(),used:false,busy:false,request:0};
async function api(path,body){const r=await fetch('/api'+path,{...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(10000)});const d=await r.json();if(!r.ok)throw Error(d.error||'연결을 확인하고 다시 시도해 주세요.');return d;}
const announce=t=>$('#live').textContent=t;
function nav(page,replace=false){S.request++;S.busy=false;S.page=page;if(replace)history.replaceState({page},'',`#${page}`);else history.pushState({page},'',`#${page}`);render();$('#screen').focus();window.scrollTo(0,0);}
function reset(){S.session=null;S.strategy=null;S.feedback.clear();S.used=false;S.filter='전체';nav('home');}
function back(){nav(S.page==='recommend'?'qr':S.page==='qr'?'detail':'home');}
window.addEventListener('popstate',e=>{S.request++;S.busy=false;S.page=S.station?(e.state?.page||'home'):'home';if(S.page==='recommend'&&!S.strategy)S.page='qr';render();});
$('#brand').onclick=e=>{e.preventDefault();reset();};$('#nav-back').onclick=back;$('#nav-reset').onclick=reset;
const steps=p=>`<ol class="flow-steps" aria-label="체험 단계">${['탐색','상세','체크인','추천'].map((n,i)=>`<li class="${i===p?'current':i<p?'completed':''}" ${i===p?'aria-current="step"':''}><span>${i<p?'✓':i+1}</span>${n}</li>`).join('')}</ol>`;
function render(){if(S.map){S.map.remove();S.map=null;}$('#nav-back').hidden=S.page==='home';$('#nav-reset').hidden=S.page==='home';({home:home,detail:detail,qr:qr,recommend:recommend}[S.page]||home)();}
function filtered(){const q=S.query.trim().toLowerCase();return S.stations.filter(s=>q?`${s.name} ${s.city}`.toLowerCase().includes(q):s.city.startsWith(S.city)).sort((a,b)=>Number(S.cases.some(c=>c.stationId===b.id))-Number(S.cases.some(c=>c.stationId===a.id)));}
function home(){ $('#screen').innerHTML=`<section class="screen-view"><div class="hero"><p class="eyebrow">CHARGE & DISCOVER</p><h1>어디에서<br><em>잠시 머물까요?</em></h1><p class="hero-copy">충전소에서 시작하는 강원의 새로운 발견</p></div><div class="home-controls"><label class="search-box">${icon('search')}<input id="search" aria-label="충전소 또는 지역 검색" placeholder="충전소 또는 지역을 검색하세요" value="${esc(S.query)}"><button id="clear" class="clear-search" aria-label="검색 지우기">×</button></label><p class="case-label">준비된 대표 지역</p><div class="region-tabs" aria-label="대표 지역">${S.cases.map(c=>`<button data-city="${esc(c.city)}" class="${!S.query&&S.city===c.city?'active':''}" aria-pressed="${!S.query&&S.city===c.city}">${esc(c.city)}</button>`).join('')}</div></div><div class="home-map"><div id="home-map" aria-label="검색된 충전소 지도"></div><span class="map-label">${icon('pin')} 충전소 위치 · 실시간 상태 아님</span></div><div class="station-section"><div class="section-title"><h2>충전소 선택</h2><span id="count"></span></div><div id="station-list" class="station-list"></div><button id="more" class="more-button">충전소 더 보기</button><p class="footnote">공개 충전소 자료 기준 · 운영 조건은 별도 확인이 필요합니다.</p><div class="notice">${icon('info')}<span>QR 체크인과 혜택은 시뮬레이션입니다.<br>‘대표 예시’ 충전소에서 전체 흐름을 확인하세요.</span></div></div></section>`;
$('#search').oninput=e=>{S.query=e.target.value;S.limit=6;updateHome();};$('#clear').onclick=()=>{S.query='';$('#search').value='';updateHome();$('#search').focus();};document.querySelectorAll('[data-city]').forEach(b=>b.onclick=()=>{S.city=b.dataset.city;S.query='';S.limit=6;homeRebuild();});$('#more').onclick=()=>{S.limit+=6;updateHome();};updateHome();}
function homeRebuild(){if(S.map){S.map.remove();S.map=null;}home();}
function updateHome(){const all=filtered(),rows=all.slice(0,S.limit);$('#count').textContent=`${all.length.toLocaleString()}곳`;$('#station-list').innerHTML=rows.length?rows.map(s=>`<button class="station-row ${S.cases.some(c=>c.stationId===s.id)?'curated':''}" data-station="${esc(s.id)}"><span class="station-icon">${icon('bolt')}</span><span class="station-text"><strong>${esc(s.name)}</strong><small>${esc(s.city)} · 급속 ${s.fastCount} / 완속 ${s.slowCount}</small>${S.cases.some(c=>c.stationId===s.id)?'<span class="tag">대표 예시</span>':''}</span>${icon('arrow')}</button>`).join(''):`<div class="empty">${icon('search')}<h3>검색 결과가 없어요</h3><p>다른 이름으로 검색하거나 대표 지역을 선택해 주세요.</p></div>`;$('#more').hidden=all.length<=S.limit;document.querySelectorAll('[data-station]').forEach(b=>b.onclick=()=>select(b.dataset.station));document.querySelectorAll('[data-city]').forEach(b=>{const active=!S.query&&S.city===b.dataset.city;b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});makeMap('home-map',rows);}
function select(id){S.station=S.stations.find(s=>s.id===id);S.session=null;S.strategy=null;S.feedback.clear();S.used=false;S.filter='전체';nav('detail');}
function makeMap(id,rows){if(S.map){S.map.remove();S.map=null;}const el=document.getElementById(id);if(!el)return;const fail=()=>{if(!el.isConnected||el.parentElement.querySelector('.map-problem'))return;const p=document.createElement('div');p.className='map-problem';p.innerHTML='<strong>지도를 불러오지 못했어요</strong><p>충전소 목록과 체크인은 계속 이용할 수 있습니다.</p>';el.parentElement.append(p);};el.parentElement.querySelector('.map-problem')?.remove();if(!window.L){fail();return;}const map=L.map(el,{scrollWheelZoom:false}).setView([37.75,128.2],8);S.map=map;const offline=new URLSearchParams(location.search).get('map')==='offline';const tiles=L.tileLayer(offline?'/offline-map/{z}/{x}/{y}.png':'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors',maxZoom:19}).addTo(map);tiles.on('tileerror',fail);const points=[];rows.forEach(s=>{if(!Number.isFinite(s.lat)||!Number.isFinite(s.lng))return;points.push([s.lat,s.lng]);const marker=L.marker([s.lat,s.lng],{title:s.name,keyboard:true,icon:L.divIcon({className:'',html:'<span class="marker">'+icon('bolt')+'</span>',iconSize:[32,32]})}).addTo(map);const markerEl=marker.getElement();const activate=e=>{e.stopPropagation();if(S.page==='home')select(s.id);};markerEl.addEventListener('click',activate);markerEl.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate(e);}});});if(points.length)map.fitBounds(points,{padding:[30,30],maxZoom:14});}
function detail(){const s=S.station,r=S.regions.find(r=>r.city===s.city||r.city.startsWith(s.city));$('#screen').innerHTML=`<section class="screen-view"><div class="detail-hero"><p class="eyebrow">YOUR STARTING POINT</p><p class="city-line">${icon('pin')}${esc(s.city)}</p><h1>${esc(s.name)}</h1></div>${steps(1)}<div class="content"><p class="detail-label">설치된 충전기</p><div class="spec-grid"><div class="spec"><span class="spec-top">${icon('bolt')} 급속</span><strong>${s.fastCount}<small>기</small></strong></div><div class="spec"><span class="spec-top">${icon('bolt')} 완속</span><strong>${s.slowCount}<small>기</small></strong></div><p class="footnote">설치 수 기준이며 실시간 이용 가능 상태가 아닙니다.</p><div class="detail-map"><div id="detail-map" aria-label="선택 충전소 위치"></div></div><p class="detail-location">${icon('pin')}${esc(s.city)} · 공개 자료의 충전소 좌표</p><details class="insight"><summary>이 지역의 관광 연결 유형 ${icon('info')}</summary><p>${r?esc(r.segment):'지역 분류 정보 확인 필요'}. A_dest(관광지 접근성)·A_route(도로 접근성)로 분류한 시군 단위 분석입니다. 개별 충전소의 보행 접근성을 보장하지 않습니다.</p><p>D는 방문·소비 각 50%의 관광수요 지표이며, D·U는 분류축이 아닌 사례 선정 검토용입니다. 이 앱은 다섯 개 지역의 대표 사례를 담고 있습니다.</p></details><div class="notice">${icon('info')}<span>실제 충전을 시작하지 않습니다.<br>체크인 후 준비된 주변 장소 예시를 살펴보세요.</span></div><div class="actions"><button id="checkin-start" class="primary">모의 체크인 시작 ${icon('arrow')}</button></div></div></section>`;$('#checkin-start').onclick=()=>nav('qr');makeMap('detail-map',[s]);}
function qr(){ $('#screen').innerHTML=`<section class="screen-view">${steps(2)}<div class="content qr-screen"><p class="eyebrow">SIMULATED CHECK-IN</p><h1>작은 체크인,<br>새로운 탐색.</h1><p class="subcopy">충전소에 도착한 상황을 가정해<br>버튼으로 QR 스캔을 체험하세요.</p><div class="scanner" aria-hidden="true">${icon('qr')}<span class="scan-line"></span><span class="scan-corner"></span></div><p class="scanner-caption">QR 스캔 · 카메라를 사용하지 않습니다</p><p class="selected-station">${icon('bolt')}${esc(S.station.name)}</p><div class="notice">${icon('info')}<span>실제 충전기 인증이나 방문 인증이 아닙니다.<br>스캔 버튼은 체크인 세션만 생성합니다.</span></div><div id="checkin-error" role="alert"></div><div class="actions"><button id="scan" class="primary">모의 스캔 완료 ${icon('check')}</button><button id="qr-back" class="secondary">충전소 다시 확인</button></div></div></section>`;$('#scan').onclick=scan;$('#qr-back').onclick=()=>nav('detail');}
async function scan(){if(S.busy)return;S.busy=true;const token=++S.request;$('#scan').disabled=true;$('#scan').textContent='주변 정보를 준비하고 있어요…';try{if(!S.session){const d=await api('/checkin',{stationId:S.station.id});if(token!==S.request)return;S.session=d.sessionId;}const d=await api(`/stations/${encodeURIComponent(S.station.id)}/strategy`);if(token!==S.request)return;S.strategy=d;nav('recommend');}catch(e){if(token!==S.request)return;$('#checkin-error').textContent=e.message;$('#scan').disabled=false;$('#scan').textContent='다시 시도';}finally{if(token===S.request)S.busy=false;}}
function recommend(){const d=S.strategy,places=d.places.filter(p=>S.filter==='전체'||p.category===S.filter);$('#screen').innerHTML=`<section class="screen-view"><div class="recommend-hero"><p class="eyebrow">YOUR NEXT DISCOVERY</p><h1>${esc(d.title)}</h1><p>${esc(d.description)}</p><span class="station-crumb">${icon('bolt')}${esc(S.station.name)}</span></div>${steps(3)}<div class="content"><details class="benefit" open><summary>${icon('gift')}<span><strong>${esc(d.cta?d.cta.reward:d.benefitTitle||'여행의 작은 혜택')}</strong><small>${esc(d.benefitSubtitle||'')}</small></span><span>＋</span></summary><div class="benefit-body">${d.cta?`<p>${esc(d.benefitTitle||'')}</p><button id="benefit" class="secondary" ${S.used?'disabled':''}>${S.used?'확인 완료':esc(d.cta.label)}</button><p class="benefit-note" id="benefit-note">${S.used?'* 실제 서비스에서는 이 시점에 사용 이력이 서버로 전송되어 쿠폰 재사용을 막습니다.':'직원 확인이나 매장 제시는 필요하지 않습니다.'}</p>`:''}</div></details><div class="section-title"><h2>주변 장소</h2><span>${d.source==='curated'?'대표 사례':d.source==='external'?'외부 검색 정보':'준비된 정보 없음'}</span></div><div class="filter-row" aria-label="장소 선호 필터">${['전체','음식점','카페','관광지'].map(f=>`<button data-filter="${f}" class="${S.filter===f?'active':''}" aria-pressed="${S.filter===f}">${f}</button>`).join('')}</div><div class="places">${places.length?places.map(p=>`<article class="place-card"><div class="place-body"><span class="place-symbol">${icon(p.category==='음식점'?'food':p.category==='카페'?'coffee':'mountain')}</span><div class="place-info"><span>${esc(p.category)}</span><h3>${esc(p.name)}</h3>${Number.isFinite(p.distanceM)?`<small>${p.distanceM}m · 도보 ${p.walkMin}분</small>`:''}<a href="https://map.naver.com/p/search/${encodeURIComponent(S.station.city+' '+p.name)}" target="_blank" rel="noopener noreferrer">지도에서 정보 확인 ↗</a></div></div></article>`).join(''):`<div class="empty">${icon('pin')}<h3>${d.places.length?'선택한 분류의 예시가 없어요':'준비된 장소 예시가 없어요'}</h3><p>정보가 부족하다는 뜻이며 주변 시설이 없다는 의미는 아닙니다.</p><button id="empty-action" class="secondary">${d.places.length?'전체 예시 보기':'다른 지역 선택'}</button></div>`}</div><p class="footnote">${esc(d.notice)} 장소의 운영 여부와 이동 경로는 별도 확인이 필요합니다.</p><div class="feedback"><h2>이런 안내는 어떠셨나요?</h2><p>방문 인증이 아닌 체험 의견으로 저장됩니다.</p><div class="feedback-buttons">${[['helpful','도움이 됐어요'],['interested','방문해 보고 싶어요']].map(([type,label])=>`<button data-feedback="${type}" class="secondary" ${S.feedback.has(type)?'disabled':''}>${S.feedback.has(type)?'✓ ':''}${label}</button>`).join('')}</div><p id="feedback-status" class="feedback-status" role="status">${S.feedback.size?'의견을 저장했습니다. 같은 세션의 중복 응답은 저장하지 않습니다.':''}</p></div><div class="actions"><button id="another" class="primary">다른 충전소 선택 ${icon('arrow')}</button></div></div></section>`;
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{S.filter=b.dataset.filter;recommend();document.querySelector(`[data-filter="${S.filter}"]`).focus();});$('#empty-action')?.addEventListener('click',()=>{if(d.places.length){S.filter='전체';recommend();}else reset();});$('#benefit')?.addEventListener('click',()=>{S.used=true;recommend();announce('쿠폰 확인 완료');});document.querySelectorAll('[data-feedback]').forEach(b=>b.onclick=()=>feedback(b));$('#another').onclick=reset;}
async function feedback(b){const type=b.dataset.feedback,session=S.session;b.disabled=true;try{await api('/feedback',{stationId:S.station.id,sessionId:session,type});if(session!==S.session)return;S.feedback.add(type);b.textContent='✓ '+b.textContent;const el=$('#feedback-status');if(el)el.textContent='의견을 저장했습니다. 같은 세션의 중복 응답은 저장하지 않습니다.';}catch(e){b.disabled=false;if($('#feedback-status'))$('#feedback-status').textContent=e.message;}}
(async()=>{try{const [stations,cases,analysis]=await Promise.all([api('/stations'),api('/cases'),api('/analysis')]);S.stations=stations;S.cases=cases.cases;S.regions=analysis.regions;nav('home',true);}catch(e){$('#screen').innerHTML=`<div class="content error-message"><h1>연결을 확인해 주세요</h1><p>${esc(e.message)}</p><button class="primary" id="retry">다시 연결하기</button></div>`;$('#retry').onclick=()=>location.reload();}})();
